In [10]:
import pandas as pd

df = pd.read_csv('EDA/부산_202310.csv')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9501 entries, 0 to 9500
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   순번                 9501 non-null   int64
 1   호출부호               9501 non-null   object
 2   입항횟수               9501 non-null   int64
 3   입항횟수.1             9501 non-null   int64
 4   입항횟수.2             9501 non-null   int64
 5   신고톤수               9501 non-null   object
 6   선박명                9501 non-null   object
 7   선사/대리점             9501 non-null   object
 8   선사/대리점.1           9501 non-null   object
 9   신청시설               9501 non-null   object
 10  신청시설.1             9501 non-null   object
 11  신청시설.2             9501 non-null   object
 12  신청일시(FROM ~ TO)    9501 non-null   object
 13  신청일시(FROM ~ TO).1  9501 non-null   object
 14  지정시설               7486 non-null   object
 15  지정시설.1             7486 non-null   object
 16  지정시설.2             7486 non-null   object
 17  지정일시(FROM ~ TO)    7486 non-null   object
 18  지정일시(FROM ~ TO).1  7486 non-null   object
 19  사용목적명              9501 non-null   object
 20  예보일시               9501 non-null   object
 21  허가유무               9501 non-null   object
dtypes: int64(4), object(18)
memory usage: 1.6+ MB

In [9]:
ddf = df[df['사용목적명'] == '접안대기']

In [12]:
ddf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1774 entries, 0 to 9495
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   순번                 1774 non-null   int64
 1   호출부호               1774 non-null   object
 2   입항횟수               1774 non-null   int64
 3   입항횟수.1             1774 non-null   int64
 4   입항횟수.2             1774 non-null   int64
 5   신고톤수               1774 non-null   object
 6   선박명                1774 non-null   object
 7   선사/대리점             1774 non-null   object
 8   선사/대리점.1           1774 non-null   object
 9   신청시설               1774 non-null   object
 10  신청시설.1             1774 non-null   object
 11  신청시설.2             1774 non-null   object
 12  신청일시(FROM ~ TO)    1774 non-null   object
 13  신청일시(FROM ~ TO).1  1774 non-null   object
 14  지정시설               1254 non-null   object
 15  지정시설.1             1254 non-null   object
 16  지정시설.2             1254 non-null   object
 17  지정일시(FROM ~ TO)    1254 non-null   object
 18  지정일시(FROM ~ TO).1  1254 non-null   object
 19  사용목적명              1774 non-null   object
 20  예보일시               1774 non-null   object
 21  허가유무               1774 non-null   object
dtypes: int64(4), object(18)
memory usage: 318.8+ KB

In [14]:
ddf.to_csv('부산_접안대기_202310.csv', index = False, encoding = 'utf-8-sig')

,순번,호출부호,입항횟수,입항횟수.1,입항횟수.2,신고톤수,선박명,선사/대리점,선사/대리점.1,신청시설,...,신청일시(FROM ~ TO),신청일시(FROM ~ TO).1,지정시설,지정시설.1,지정시설.2,지정일시(FROM ~ TO),지정일시(FROM ~ TO).1,사용목적명,예보일시,허가유무
0,1,9V8011,2023,42,1,7.464,PACIFIC TIANJIN,ICZ0830,흥아라인(주),WAN,...,2023-10-01 04:00,2023-10-02 09:00,MBR,03,감만부두 3선석,2023-10-01 04:00,2023-10-02 09:00,접안대기,2023-10-01,허가완료
9,10,DSEK8,2023,56,1,3.994,SUNNY PALM,KMS8832,고려해운(주),MB6,...,2023-10-01 14:00,2023-10-02 06:00,MB6,04,자성대부두 64선석,2023-10-01 14:00,2023-10-02 06:00,접안대기,2023-10-01,허가완료
11,12,9V7921,2023,27,1,9.962,PACIFIC GENEVA,OSL0038,장금상선(주),WAN,...,2023-10-01 16:00,2023-10-03 18:00,MBR,04,감만부두 4선석,2023-10-01 16:00,2023-10-03 18:00,접안대기,2023-10-01,허가완료
21,22,DSQX4,2023,2,1,4.562,LEPUS,BSC2203,주식회사 스완쉬핑,WAN,...,2023-10-01 13:30,2023-10-03 08:00,MKC,04,감천 중앙부두 4선석,2023-10-01 13:30,2023-10-03 08:00,접안대기,2023-10-01,허가완료
29,30,DSFU2,2023,115,3,21.688,PANSTAR DREAM,KMC0725,(주)팬스타라인닷컴,MBF,...,2023-10-01 09:00,2023-10-01 15:00,MBF,12,신국제여객터미널 12선석,2023-10-01 09:00,2023-10-01 15:00,접안대기,2023-10-01,허가완료
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9491,9492,835523,2023,5,46,74,동진1호,BSB2508,동진선박,MYP,...,2023-10-27 14:57,2023-10-27 15:54,NaN,NaN,NaN,NaN,NaN,접안대기,2023-10-31,미허가
9492,9493,835523,2023,5,47,74,동진1호,BSB2508,동진선박,MWB,...,2023-10-27 16:08,2023-10-27 17:00,NaN,NaN,NaN,NaN,NaN,접안대기,2023-10-31,미허가
9493,9494,835523,2023,5,48,74,동진1호,BSB2508,동진선박,MYP,...,2023-10-27 17:17,2023-10-28 11:55,NaN,NaN,NaN,NaN,NaN,접안대기,2023-10-31,미허가
9494,9495,835523,2023,5,49,74,동진1호,BSB2508,동진선박,*SD,...,2023-10-28 17:45,2023-10-29 08:35,NaN,NaN,NaN,NaN,NaN,접안대기,2023-10-31,미허가
9495,9496,835523,2023,5,50,74,동진1호,BSB2508,동진선박,MYP,...,2023-10-29 14:07,2023-10-31 13:48,NaN,NaN,NaN,NaN,NaN,접안대기,2023-10-31,미허가